<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63bf0f991067a',
	'title' => 'Staff SMS Messages',
	'fields' => array(
		array(
			'key' => 'field_63bf17cbc4e50',
			'label' => 'Message Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6570afefef4df',
			'label' => '(Column 8/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '8/12',
			'endpoint' => 0,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_68dbf38cdcb84',
			'label' => 'Sending Phone Number',
			'name' => 'sms_msg_from',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'choices' => array(
				'+16058845559' => 'Eide Alerts (Default) (6058845559)',
				'+16054446666' => 'Human Resources (6054446666)',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_custom' => 0,
			'search_placeholder' => '',
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_63bf1a8ae121e',
			'label' => 'Scheduled Message',
			'name' => 'scheduled_message',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_63bf16abee102',
					'label' => 'Scheduled Message?',
					'name' => 'sms_msg_scheduled',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'custom_role_permissions' => array(
						0 => 'editor',
						1 => 'businessmanager',
					),
					'message' => '',
					'default_value' => 0,
					'allow_in_bindings' => 1,
					'ui_on_text' => 'Scheduled',
					'ui_off_text' => 'Send Now',
					'ui' => 1,
				),
				array(
					'key' => 'field_63bf16f7ee103',
					'label' => 'Set Scheduled Date',
					'name' => 'sms_msg_scheduled_date',
					'aria-label' => '',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_63bf16abee102',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'custom_role_permissions' => array(
						0 => 'editor',
						1 => 'businessmanager',
					),
					'display_format' => 'm/d/Y g:i a',
					'return_format' => 'Y-m-d H:i',
					'first_day' => 0,
					'default_to_current_date' => 1,
					'allow_in_bindings' => 1,
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_63bf12f1f1157',
			'label' => 'SMS Message Text',
			'name' => 'sms_msg_text',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'readonly' => 0,
			'disabled' => 0,
			'maxlength' => 1400,
			'allow_in_bindings' => 1,
			'rows' => 10,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6570b01def4e0',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_63bf11d6dea5b',
			'label' => 'MMS Media',
			'name' => 'sms_msg_image',
			'aria-label' => '',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => 'Upload an optional image to be included in the message. It will be sent before your message.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'crop_type' => 'free_crop',
			'return_format' => 'array',
			'preview_size' => 'large',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => 2,
			'mime_types' => '.jpeg,.jpg,.gif,.png',
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_6570b026ef4e1',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'columns' => '6/12',
		),
		array(
			'key' => 'field_63bf17a7c4e4f',
			'label' => 'Message Recipient Filters',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 1,
			'selected' => 0,
		),
		array(
			'key' => 'field_6570b12c69c6c',
			'label' => 'Using Filters',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'message' => 'The filters below will group the recipients who will receive the message. Choose the Toggle All under either Locations or Departments to select all contacts in those groups. <i>(Ex. To send to all Sales Staff in multiple locations choose the "Locations" first to include, then choose the department "Sales")</i>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_63bf0f99b7cb9',
			'label' => 'Location(s)',
			'name' => 'sms_msg_location',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'col-md-6 two-columns',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'taxonomy' => array(
				0 => 'location',
			),
			'allow_terms' => '',
			'allow_level' => '',
			'field_type' => 'checkbox',
			'default_value' => array(
			),
			'return_format' => 'id',
			'layout' => 'vertical',
			'toggle' => 1,
			'save_terms' => 1,
			'load_terms' => 0,
			'allow_in_bindings' => 1,
			'choices' => array(
			),
			'ui' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'search_placeholder' => '',
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'key' => 'field_63bf1006b7cba',
			'label' => 'Department(s)',
			'name' => 'sms_msg_department',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'col-md-6 two-columns',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'taxonomy' => array(
				0 => 'department',
			),
			'allow_terms' => '',
			'allow_level' => '',
			'field_type' => 'checkbox',
			'default_value' => array(
			),
			'return_format' => 'id',
			'layout' => 'vertical',
			'toggle' => 1,
			'save_terms' => 1,
			'load_terms' => 0,
			'allow_in_bindings' => 1,
			'choices' => array(
			),
			'ui' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'search_placeholder' => '',
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'key' => 'field_6570e19a54879',
			'label' => '# Recipients',
			'name' => 'sms_recipients_number',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'default_value' => '',
			'readonly' => 0,
			'disabled' => 0,
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6570e10c34bde',
			'label' => 'Recipient Names',
			'name' => 'sms_recipients',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_role_permissions' => array(
				0 => 'editor',
				1 => 'businessmanager',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'readonly' => 0,
			'disabled' => 0,
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'staff-sms',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'block_editor',
		2 => 'the_content',
		3 => 'excerpt',
		4 => 'discussion',
		5 => 'comments',
		6 => 'slug',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => 'SMS Message Options',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => array(
		'63f651abe8b9a' => array(
			'acfe_meta_key' => 'staff_sms_msg_sent',
			'acfe_meta_value' => '0',
		),
		'68dc2982d18fe' => array(
			'acfe_meta_key' => 'staff_sms_msg_sent_datetime',
			'acfe_meta_value' => '',
		),
	),
	'acfe_note' => '',
	'modified' => 1759421417,
));

endif;